### ISSUE TITLE
[GOV] Nomination of @memo330179 for Project Maintainer

### ISSUE THREAD

**Issue by RobertHosking** [project-rainstorm/project_rainstorm#3]
I hereby nominate @memo330179 for the role of project maintainer. The nomination will be ratified upon being seconded and unanimously agreed. This motion will achieve unanimous agreement if there are no objections voiced below in the span of 3 days. By this definition, @memo330179 will be given the role of PM this upcoming weekend.

**Comment by davisv7** [comment]
Second!

**Comment by RobertHosking** [comment]
It is done
