### ISSUE TITLE
[API] get installation status of a service

### ISSUE THREAD

**Issue by nullcount** [project-rainstorm/project_rainstorm#32]
When you first enable a service, it will pull and extract the images required. In this time, the service is neither disabled, nor enabled, rather it is 'Installing'.

We need some way to indicate this to the user. A progress bar would be dope but simply knowing that the service is "downloading", or "extracting" or simply just "installing" is good enough.

**Comment by RobertHosking** [comment]
I think it can be solved in the front-end.

When the user clicks "enable" this will trigger a `setInterval` that checks the status of the service every second until it shows `Enabled` In the meantime, we'll just render "Enabling...." or something generic that works both in the installation case as well as the regular enable case.

**Comment by nullcount** [comment]
Closing this in favor of a new issue requiring 3 service states: Enabled, Disabled, and Never installed
