### ISSUE TITLE
[API] services - combine actions

### ISSUE THREAD

**Issue by nullcount** [project-rainstorm/project_rainstorm#33]
When we render the main page with all the services, we need lots of information. Instead of making lots of network requests in a loop to get this info, let's make one endpoint that gets all of it. 

It should return an array of all services:
```
{
name: service name (folder name)
status: service status 
settings: service.json
}
```
Each service folder will have a file called `service.json`. This file will have information about the service like label, description, special instructions, helpful links, user-defined variables, etc. Just put the contents of the file in a key called `settings'.

**Comment by WillHHippo** [comment]
The reason I didn't combine these in #30 is that that to get the status for a service we have to check against docker-compose which is a slow process. If there was a way to persist the status, it would be much faster.

**Comment by WillHHippo** [comment]
splitting out setting for more discussion

**Comment by nullcount** [comment]
I think #46 covers this
