### ISSUE TITLE
[GUI] Build the HTML/CSS for the interface

### ISSUE THREAD

**Issue by RobertHosking** [project-rainstorm/project_rainstorm#4]
I will design and build the HTML/CSS for the primary interface. This will make it easy to include in Django templates for rendering.

**Comment by memo330179** [comment]
Does this include implementation as well or is it only the design. @newswangerd are you going to take care of the Django portion?

**Comment by RobertHosking** [comment]
This issue includes implementation of an HTML/CSS static page for just the homepage. Making it work with Django should be another issue. There are potentially other pages (server settings, app settings, login page) but those are out of scope for MVP.

**Comment by RobertHosking** [comment]
Commit 032f933 includes this work
