### ISSUE TITLE
[BUILD] Get a .IMG build system

### ISSUE THREAD

**Issue by RobertHosking** [project-rainstorm/project_rainstorm#5]
Since the app is meant to be used by RasPi, we will release a .img file to be flashed to the sd card. Anyone is welcome to clone the repo and run it in development or production that way, but since the services will likely need OS-level configuration (firewalls, subdomains, etc) it's best to include them all in an .img file.

As far as building the .img, there's probably a fancy way to generate them but, starting out, I'm going to write Ansible scripts that define the configuration of the OS and commit them to this repo. When it is time to release a Build, I will run the scripts against a fresh install of the OS on an actual RasPi and create a .IMG from the SD card by cloning it on a separate computer.

**Comment by RobertHosking** [comment]
Before I get started on this, I need to know what OS we're using. Do we think BalenaOS is easy enough to quickly get an MVP? Or should we use something more familiar?

**Comment by RobertHosking** [comment]
Researching BalenaOS... pretty neat! It's meant to use alongside a CLI toolkit running from a local machine. 

Using the toolkit, you can:

- apply some configuration to the .img file before flashing to SD
- discover the box and connect via ssh
- push local containers (dockerfiles or docker-compose) to the box to be built and run

The toolkit feels like a minimal version of Ansible (without the scripting via playbooks).

I am thinking that each service will be a container and Rainstorm will also be a container. Since Rainstorm is in a container, I'm not sure how it can control other containers. Originally, I had imagined that Rainstorm would run on the bare metal. Hopefully @newswangerd has some insight.

I'm going to install it on a Pi and push a Plex container to it.

**Comment by RobertHosking** [comment]
Giving up on BalenaOS. It is useful for getting containers in a stateless OS but we need the non-techie users to manually start/stop containers and Balena doesn't allow docker access.

I have a minimal Manjaro image laying around, I'll start again with that as the base.

**Comment by newswangerd** [comment]
@RobertHosking you can control docker on the host from a container by mounting the docker socket into the container. 

I've had pretty good luck with Ubuntu server for the pi: https://ubuntu.com/download/raspberry-pi

**Comment by newswangerd** [comment]
Running the core app baremetal might be better because then we won't accidentally shut down the core service

**Comment by WillHHippo** [comment]
What's the status on this? Can we break up it further?

**Comment by nullcount** [comment]
This issue has kinda turned in to "Create the first release". Agree that the scope is too large. 

The first release images will be created by cloning the repo on a new Pi, running the setup script, then cloning the SD card, running some fancy gparted commands to shrink the IMG, then releasing that for others to flash.

The intention of the issue was to figure out how to release IMG files, so since we have an idea, I guess it can close.
