### ISSUE TITLE
[API] run the change password script

### ISSUE THREAD

**Issue by nullcount** [project-rainstorm/project_rainstorm#52]
Check the app routes for password related endpoints. Add or complete the method for changing the password. It should call a script like this `bash ~/project_rainstorm/scripts/pw_change.sh <new_password>` where the password is passed as an argument to the script.

The method should check the exit code of the script. If the exit code is zero, then its a success, return a "success" response. If the exit code is 1, send a "Error response".

**Comment by ravindrabhargava** [comment]
interesting, would like to work on it. please assign to me.

/assign

**Comment by WillHHippo** [comment]
@ravindrabhargava let me know if you have any questions.

**Comment by nullcount** [comment]
@ravindrabhargava you should probably work from the `setup-script` branch. Or just wait until this PR gets merged (#47). That way you will have the new `pw_change.sh` script.

Also, ignore the comments in the `__init__.py` file where the `/settings/password` endpoint is defined. They are outdated. Follow the issue instructions above.

**Comment by nullcount** [comment]
There has been a change in how passwords are managed. This issue is no longer accurate. Closing and creating a new one.
