### ISSUE TITLE
[API] JWT Auth with flask

### ISSUE THREAD

**Issue by nullcount** [project-rainstorm/project_rainstorm#53]
Our API will have a JSON Web Token authentication. The frontend will authenticate and be granted a token. The token will be provided to the app along with every request to successfully retrieve data or preform actions.

Follow this guide:
https://iq.opengenus.org/jwt-authentication-flask/

**Comment by WillHHippo** [comment]
Working on this now

I will also move the flask configuration to env variables

**Comment by WillHHippo** [comment]
Moving out refresh token to another issue
