### ISSUE TITLE
[DISCUSSION] License

### ISSUE THREAD

**Issue by memo330179** [project-rainstorm/project_rainstorm#6]
What should this be licensed under? The project is available for all to see, so we should include a license to go along with it.

**Comment by RobertHosking** [comment]
We seem to have a similar model to mynodebtc. They're using the CC license with some modifications: https://github.com/mynodebtc/mynode/blob/master/LICENSE.md

**Comment by newswangerd** [comment]
I just want a license that lets people use and modify the code, but doesn't allow them to commercialize it.

**Comment by memo330179** [comment]
In that case, I think that https://creativecommons.org/licenses/by-nc-sa/4.0/ is the best option. Are there any modifications that should be made?

**Comment by benrquesada** [comment]
No I think those 3 options under a creative commons license should suffice.

**Comment by RobertHosking** [comment]
Seconded

**Comment by WillHHippo** [comment]
closing because pr was merged in
