### ISSUE TITLE
[BUILD] Simple Shared Authentication

### ISSUE THREAD

**Issue by RobertHosking** [project-rainstorm/project_rainstorm#7]
One benefit we'd like to get from all this effort is having the admin user for each app set automatically with a shared password. For example, if I enable Nextcloud, Plex, and Rocket Chat for the first time, the compose script will auto-create a privileged user in each of those apps with the node admin's password. 

While not really required for an MVP, having an auth system in place will make it easier to write the compose files as we add them.

Requirements:

- [ ] Require the user to authenticate before accessing the app. There will only ever be one user of this app -- an admin/root user. By default, the user has a simple password.
- [ ] If the default password is still set, show a password hint at login screen. (Hint: default password is 'rain') Show warning on home screen if default password still set.
- [ ] Allow user to change password from settings.
- [ ] This password should also be the root user's password in the OS. Then the user could `ssh root@rainstorm` and login with their password set from the web GUI.
- [ ] This password should be securely stored somewhere where docker can read it for automatically setting admin user credentials when starting new containers.

**Comment by nullcount** [comment]
Here's how to do auth:
1. Our app has no need for a database. We can get everything we need from querying the FS or docker socket. For auth in the core app, compare the entered password to a stored hash in a file somewhere
2. When changing password do some basic validation in the app to make sure that the entered password is different than the existing password and also that the confirm password field matches. Then call a bash script and pass the entered password as an argument.
3. The script should change the linux password `echo "user:$PASSWORD" | chpasswd`
4. The script should issue a command for each app that has a programatic way to change password. Nextcloud and Filerun have php scripts that do this. Call `docker exec` to issue the command in the container.

Something to think about... if the container has been enabled but is currently disabled, then `docker exec` will not work and the password will remain unchanged for that service when it is enabled again. How best to handle this case?

**Comment by nullcount** [comment]
I have a good idea how this should work. Will break up into smaller issues.
