### ISSUE TITLE
[BUILD] The App API

### ISSUE THREAD

**Issue by RobertHosking** [project-rainstorm/project_rainstorm#8]
As far as the API goes I think we need to

- get list of all services
This can be done by just scanning filesystem for folders in the `services` directory
- get list of running services
Can get this by asking docker
- start a service
Run `docker-compose up -d` on the `docker-compose.yml` file in the service folder. (i.e. `services/<service_name>/docker-compose.yml`)
- stop a service
Run `docker-compose down` on the service's docker-compose file
- configure env variables on a service
May not be necessary for MVP but should design in such a way that makes it easy to add later
- Log in
- Log out
- change password
We want to store the password encrypted somewhere so it can be accessed by the other containers to use as the defualt passwords. Maybe this isn't and MVP requirement either. Basic auth to access the control panel is required. See #7

**Comment by WillHHippo** [comment]
This can be broken up into.

- Set up web app framework
- Set up API endpoint to get list of all services
- Set up API endpoint to get list of running services
- Add ability to start a service
- Add ability to stop a service
- Add ability configure env variables on a service
- Add authentication ability

**Comment by WillHHippo** [comment]
If we agree with the above, I will create issues for each of those items. Setting up the web app framework is a blocker for the rest, but after that, we can split up the work to whoever wants to pick them up.

**Comment by WillHHippo** [comment]
I added issues for each of the items here @count-null are we good to close this one?
