### ISSUE TITLE
[BUG] React error when enabling or disabling a service

### ISSUE THREAD

**Issue by nullcount** [project-rainstorm/project_rainstorm#81]
When you try to disable a service: TypeError: service is undefined 
The problem is with line 74 in src/Components/ServiceView/ActionList/index.js

**Comment by WillHHippo** [comment]
Fixed the authentication issue but I get errors when trying to enable
`subprocess.CalledProcessError: Command 'bash /home/memoya/project_rainstorm/services/pihole/install.sh' returned non-zero exit status 127`
