### ISSUE TITLE
[SETUP] Must re-clone git repo to work on project from drop user

### ISSUE THREAD

**Issue by davisv7** [project-rainstorm/project_rainstorm#99]
The first issue is that you'll have to reconfigure git credentials for the drop user.

I was not able to make commits to the cloned repo from the drop user even after reconfiguration. My work around was to reclone the git repo, and now it works fine. In the future, [this may be the best practice](https://serverfault.com/questions/26954/how-do-i-share-a-git-repository-with-multiple-users-on-a-machine/113688#113688), replacing group with whatever group drop and pi are both a part of.

**Comment by asharron** [comment]
Good point. Instead of our setup instructions recommending cloning the repo to run the setup script, how about we include a curl or wget command to fetch and run the setup script?

**Comment by nullcount** [comment]
A curl install would be great. The only reason for cloning first is to give he user a chance to edit the config.yml file for a custom installation. It also imports functions from functions.sh. 

If the setup script were modified to get these values some other way, it could executed with curl. 

Perhaps download and edit the config file, then run curl?

**Comment by nullcount** [comment]
I modified the setup script to work as I described above. The README has been updated with the new installation process. Now the user only clones the repo when they are already logged in as drop user.
